insert into public.scholarships (title, provider_name, amount, living_allowance, funding_type, levels, countries, deadline, duration, requirements, description, apply_url, is_featured, status) values
(
  'LPDP Reguler 2026',
  'LPDP – Kemenkeu RI',
  'Biaya pendidikan penuh',
  'Rp 7.500.000 / bulan',
  'full',
  array['s1','s2','s3'],
  array['Indonesia','Luar Negeri'],
  '2026-07-31',
  '4 tahun (S1) / 2 tahun (S2) / 4 tahun (S3)',
  array['WNI aktif','IPK min 3.00 (S2/S3)','Usia maks 35 tahun (S2) / 40 tahun (S3)','Surat rekomendasi'],
  'Beasiswa bergengsi dari Lembaga Pengelola Dana Pendidikan untuk putra-putri terbaik Indonesia yang ingin melanjutkan studi ke jenjang magister dan doktoral di dalam maupun luar negeri.',
  'https://beasiswalpdp.kemenkeu.go.id',
  true,
  'active'
),
(
  'Beasiswa Unggulan Kemendikbud',
  'Kemendikbudristek',
  'Biaya pendidikan + biaya hidup',
  'Rp 1.400.000 / bulan',
  'full',
  array['s1','s2','s3'],
  array['Indonesia'],
  '2026-07-10',
  '4 tahun (S1) / 2 tahun (S2)',
  array['WNI','Diterima di PTN/PTS terakreditasi A','IPK min 3.25','Tidak sedang menerima beasiswa lain'],
  'Beasiswa pemerintah untuk mahasiswa berprestasi yang ingin menempuh pendidikan tinggi di perguruan tinggi terbaik Indonesia.',
  'https://beasiswaunggulan.kemdikbud.go.id',
  true,
  'active'
),
(
  'Beasiswa Djarum Plus 2026',
  'Djarum Foundation',
  'Rp 750.000 / bulan',
  null,
  'partial',
  array['s1'],
  array['Indonesia'],
  '2026-07-03',
  '1 tahun (dapat diperpanjang)',
  array['Mahasiswa S1 semester 4','IPK min 3.20','Aktif berorganisasi','Usia maks 23 tahun'],
  'Program beasiswa plus pengembangan karakter dari Djarum Foundation untuk mahasiswa S1 semester 4 yang aktif dan berprestasi.',
  'https://djarumbeasiswaplus.org',
  false,
  'active'
),
(
  'Beasiswa Bank Indonesia 2026',
  'Yayasan Beasiswa Bank Indonesia',
  'Rp 1.500.000 / bulan',
  null,
  'partial',
  array['s1','s2'],
  array['Indonesia'],
  '2026-08-15',
  '1 tahun akademik',
  array['Mahasiswa aktif PTN/PTS','IPK min 3.00','Keterlibatan sosial','Surat rekomendasi dosen'],
  'Beasiswa dari Bank Indonesia untuk mendukung mahasiswa berprestasi dengan semangat berkontribusi pada masyarakat.',
  'https://www.bi.go.id/id/tentang-bi/beasiswa',
  false,
  'active'
),
(
  'Beasiswa PPA (Peningkatan Prestasi Akademik)',
  'Kemendikbudristek',
  'Rp 400.000 / bulan',
  null,
  'partial',
  array['s1'],
  array['Indonesia'],
  '2026-06-30',
  '1 semester',
  array['Mahasiswa S1 aktif','IPK min 3.00','Tidak sedang cuti','Rekomendasi kampus'],
  'Beasiswa dari Kementerian Pendidikan untuk mendukung prestasi akademik mahasiswa aktif di seluruh perguruan tinggi Indonesia.',
  'https://puslapdik.kemdikbud.go.id',
  false,
  'active'
),
(
  'Beasiswa KIP Kuliah 2026',
  'Kemendikbudristek',
  'Biaya pendidikan penuh + biaya hidup',
  'Rp 700.000 – Rp 1.400.000 / bulan',
  'full',
  array['s1'],
  array['Indonesia'],
  '2026-08-01',
  '4–5 tahun',
  array['Lulusan SMA/SMK/MA tahun ini','Lolos SNBP/SNBT/Mandiri di PTN/PTS','Keterbatasan ekonomi','KIP atau DTKS'],
  'Program Kartu Indonesia Pintar Kuliah untuk memastikan lulusan SMA berprestasi dari keluarga kurang mampu bisa mengakses pendidikan tinggi.',
  'https://kip-kuliah.kemdikbud.go.id',
  false,
  'active'
),
(
  'Chevening Scholarship 2026/2027',
  'UK Government – Foreign Commonwealth',
  'Biaya pendidikan penuh',
  'Tunjangan hidup £1.244 / bulan',
  'full',
  array['s2'],
  array['Inggris'],
  '2026-11-04',
  '1 tahun',
  array['WNI','Min 2 tahun pengalaman kerja','Tidak sedang studi S2','Tes IELTS min 6.5','Komitmen kembali ke Indonesia'],
  'Beasiswa bergengsi dari pemerintah Inggris untuk pemimpin masa depan Indonesia yang ingin studi S2 di universitas terbaik Inggris.',
  'https://www.chevening.org/scholarship/indonesia',
  true,
  'active'
);
